server:
  port: 8082
spring:
  application:
    name: Spring-boot-tutorial
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
welcome:
  message: Hello World!
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, beans"